// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYFGMufIaPfX8OKGHXelw-kfSQy2s5xxY',
    appId: '1:258866377549:web:87aab3b0e93c40ba43bd04',
    messagingSenderId: '258866377549',
    projectId: 'vdfapp-7c806',
    authDomain: 'vdfapp-7c806.firebaseapp.com',
    storageBucket: 'vdfapp-7c806.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-1L9fyrCIC0f9ZC8EawpMuRWLpnGiDHs',
    appId: '1:258866377549:android:7646a37226d95f6943bd04',
    messagingSenderId: '258866377549',
    projectId: 'vdfapp-7c806',
    storageBucket: 'vdfapp-7c806.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWpxApg5fKyaOUCeq_C5YmaNX9dD_nFEk',
    appId: '1:258866377549:ios:97590f63c6e73d2643bd04',
    messagingSenderId: '258866377549',
    projectId: 'vdfapp-7c806',
    storageBucket: 'vdfapp-7c806.firebasestorage.app',
    iosBundleId: 'com.example.schoolline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWpxApg5fKyaOUCeq_C5YmaNX9dD_nFEk',
    appId: '1:258866377549:ios:97590f63c6e73d2643bd04',
    messagingSenderId: '258866377549',
    projectId: 'vdfapp-7c806',
    storageBucket: 'vdfapp-7c806.firebasestorage.app',
    iosBundleId: 'com.example.schoolline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYFGMufIaPfX8OKGHXelw-kfSQy2s5xxY',
    appId: '1:258866377549:web:dbec1f82545f470143bd04',
    messagingSenderId: '258866377549',
    projectId: 'vdfapp-7c806',
    authDomain: 'vdfapp-7c806.firebaseapp.com',
    storageBucket: 'vdfapp-7c806.firebasestorage.app',
  );
}
